(cl:in-package ximea_ros_cam-msg)
(cl:export '(HEADER-VAL
          HEADER
          SIZE-VAL
          SIZE
          BP_SIZE-VAL
          BP_SIZE
          FRM-VAL
          FRM
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          NFRAME-VAL
          NFRAME
          TSSEC-VAL
          TSSEC
          TSUSEC-VAL
          TSUSEC
          GPI_LEVEL-VAL
          GPI_LEVEL
          BLACK_LEVEL-VAL
          BLACK_LEVEL
          PADDING_X-VAL
          PADDING_X
          ABSOLUTEOFFSETX-VAL
          ABSOLUTEOFFSETX
          ABSOLUTEOFFSETY-VAL
          ABSOLUTEOFFSETY
          EXPOSURE_TIME_US-VAL
          EXPOSURE_TIME_US
          GAIN_DB-VAL
          GAIN_DB
          ACQ_NFRAME-VAL
          ACQ_NFRAME
          IMAGE_USER_DATA-VAL
          IMAGE_USER_DATA
))