image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [848.52502,   0.     , 723.20866,
           0.     , 851.7588 , 585.21196,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.301300, 0.083661, -0.021223, -0.012616, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [688.97461,   0.     , 721.24853,   0.     ,
           0.     , 754.28235, 574.06464,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
