// Generated by gencpp from file dynamixel_interface/DataPorts.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_INTERFACE_MESSAGE_DATAPORTS_H
#define DYNAMIXEL_INTERFACE_MESSAGE_DATAPORTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dynamixel_interface/DataPort.h>

namespace dynamixel_interface
{
template <class ContainerAllocator>
struct DataPorts_
{
  typedef DataPorts_<ContainerAllocator> Type;

  DataPorts_()
    : header()
    , states()  {
    }
  DataPorts_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , states(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dynamixel_interface::DataPort_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dynamixel_interface::DataPort_<ContainerAllocator> >::other >  _states_type;
  _states_type states;





  typedef boost::shared_ptr< ::dynamixel_interface::DataPorts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_interface::DataPorts_<ContainerAllocator> const> ConstPtr;

}; // struct DataPorts_

typedef ::dynamixel_interface::DataPorts_<std::allocator<void> > DataPorts;

typedef boost::shared_ptr< ::dynamixel_interface::DataPorts > DataPortsPtr;
typedef boost::shared_ptr< ::dynamixel_interface::DataPorts const> DataPortsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_interface::DataPorts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_interface::DataPorts_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_interface::DataPorts_<ContainerAllocator1> & lhs, const ::dynamixel_interface::DataPorts_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.states == rhs.states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_interface::DataPorts_<ContainerAllocator1> & lhs, const ::dynamixel_interface::DataPorts_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_interface::DataPorts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_interface::DataPorts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_interface::DataPorts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_interface::DataPorts_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_interface::DataPorts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_interface::DataPorts_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_interface::DataPorts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "919597efe48a88349da09d8f46847ef6";
  }

  static const char* value(const ::dynamixel_interface::DataPorts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x919597efe48a8834ULL;
  static const uint64_t static_value2 = 0x9da09d8f46847ef6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_interface::DataPorts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_interface/DataPorts";
  }

  static const char* value(const ::dynamixel_interface::DataPorts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_interface::DataPorts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"DataPort[] states #array of Dataport messages for all dynamixels on bus\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dynamixel_interface/DataPort\n"
"string name #name of joint\n"
"uint16[] port_values #array of port GPIO values [0,1] for digital or [0,4095] for analog\n"
;
  }

  static const char* value(const ::dynamixel_interface::DataPorts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_interface::DataPorts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataPorts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_interface::DataPorts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_interface::DataPorts_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "states[]" << std::endl;
    for (size_t i = 0; i < v.states.size(); ++i)
    {
      s << indent << "  states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dynamixel_interface::DataPort_<ContainerAllocator> >::stream(s, indent + "    ", v.states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_INTERFACE_MESSAGE_DATAPORTS_H
