// Generated by gencpp from file dynamixel_interface/ServoDiags.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_INTERFACE_MESSAGE_SERVODIAGS_H
#define DYNAMIXEL_INTERFACE_MESSAGE_SERVODIAGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dynamixel_interface/ServoDiag.h>

namespace dynamixel_interface
{
template <class ContainerAllocator>
struct ServoDiags_
{
  typedef ServoDiags_<ContainerAllocator> Type;

  ServoDiags_()
    : header()
    , diagnostics()  {
    }
  ServoDiags_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , diagnostics(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dynamixel_interface::ServoDiag_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dynamixel_interface::ServoDiag_<ContainerAllocator> >::other >  _diagnostics_type;
  _diagnostics_type diagnostics;





  typedef boost::shared_ptr< ::dynamixel_interface::ServoDiags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_interface::ServoDiags_<ContainerAllocator> const> ConstPtr;

}; // struct ServoDiags_

typedef ::dynamixel_interface::ServoDiags_<std::allocator<void> > ServoDiags;

typedef boost::shared_ptr< ::dynamixel_interface::ServoDiags > ServoDiagsPtr;
typedef boost::shared_ptr< ::dynamixel_interface::ServoDiags const> ServoDiagsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_interface::ServoDiags_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_interface::ServoDiags_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_interface::ServoDiags_<ContainerAllocator1> & lhs, const ::dynamixel_interface::ServoDiags_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.diagnostics == rhs.diagnostics;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_interface::ServoDiags_<ContainerAllocator1> & lhs, const ::dynamixel_interface::ServoDiags_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_interface::ServoDiags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_interface::ServoDiags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_interface::ServoDiags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_interface::ServoDiags_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_interface::ServoDiags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_interface::ServoDiags_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_interface::ServoDiags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0c439c1a732520d1c71cd95240a273a";
  }

  static const char* value(const ::dynamixel_interface::ServoDiags_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0c439c1a732520dULL;
  static const uint64_t static_value2 = 0x1c71cd95240a273aULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_interface::ServoDiags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_interface/ServoDiags";
  }

  static const char* value(const ::dynamixel_interface::ServoDiags_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_interface::ServoDiags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"ServoDiag[] diagnostics #array of diagnostics messages for all dynamixels on bus\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dynamixel_interface/ServoDiag\n"
"string name #name of joint\n"
"uint8 id  #id on bus\n"
"string model_name #model name\n"
"uint8 error_code # error code\n"
"float64 voltage #current voltage\n"
"float64 temperature #current temperature\n"
;
  }

  static const char* value(const ::dynamixel_interface::ServoDiags_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_interface::ServoDiags_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.diagnostics);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoDiags_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_interface::ServoDiags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_interface::ServoDiags_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "diagnostics[]" << std::endl;
    for (size_t i = 0; i < v.diagnostics.size(); ++i)
    {
      s << indent << "  diagnostics[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dynamixel_interface::ServoDiag_<ContainerAllocator> >::stream(s, indent + "    ", v.diagnostics[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_INTERFACE_MESSAGE_SERVODIAGS_H
