(cl:defpackage control_logic_node-msg
  (:use )
  (:export
   "<CLAWPOSE>"
   "CLAWPOSE"
   "<CUBEPOSE>"
   "CUBEPOSE"
   "<CURRENTJOINTSTATE>"
   "CURRENTJOINTSTATE"
   "<DESJOINTSTATE>"
   "DESJOINTSTATE"
   "<DESPOSITION>"
   "DESPOSITION"
   "<TARGETJOINTSTATE>"
   "TARGETJOINTSTATE"
   "<TARGETJOINTSTATETRAJECTORY>"
   "TARGETJOINTSTATETRAJECTORY"
   "<TRAJECTORYCOMPLETE>"
   "TRAJECTORYCOMPLETE"
  ))

