// Generated by gencpp from file control_logic_node/CubePose.msg
// DO NOT EDIT!


#ifndef CONTROL_LOGIC_NODE_MESSAGE_CUBEPOSE_H
#define CONTROL_LOGIC_NODE_MESSAGE_CUBEPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_logic_node
{
template <class ContainerAllocator>
struct CubePose_
{
  typedef CubePose_<ContainerAllocator> Type;

  CubePose_()
    : position()
    , colour()  {
      position.assign(0.0);
  }
  CubePose_(const ContainerAllocator& _alloc)
    : position()
    , colour(_alloc)  {
  (void)_alloc;
      position.assign(0.0);
  }



   typedef boost::array<float, 4>  _position_type;
  _position_type position;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _colour_type;
  _colour_type colour;





  typedef boost::shared_ptr< ::control_logic_node::CubePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_logic_node::CubePose_<ContainerAllocator> const> ConstPtr;

}; // struct CubePose_

typedef ::control_logic_node::CubePose_<std::allocator<void> > CubePose;

typedef boost::shared_ptr< ::control_logic_node::CubePose > CubePosePtr;
typedef boost::shared_ptr< ::control_logic_node::CubePose const> CubePoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_logic_node::CubePose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_logic_node::CubePose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_logic_node::CubePose_<ContainerAllocator1> & lhs, const ::control_logic_node::CubePose_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.colour == rhs.colour;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_logic_node::CubePose_<ContainerAllocator1> & lhs, const ::control_logic_node::CubePose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_logic_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_logic_node::CubePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_logic_node::CubePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_logic_node::CubePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_logic_node::CubePose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_logic_node::CubePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_logic_node::CubePose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_logic_node::CubePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7da6dd3707216b2a7871c249c47975fa";
  }

  static const char* value(const ::control_logic_node::CubePose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7da6dd3707216b2aULL;
  static const uint64_t static_value2 = 0x7871c249c47975faULL;
};

template<class ContainerAllocator>
struct DataType< ::control_logic_node::CubePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_logic_node/CubePose";
  }

  static const char* value(const ::control_logic_node::CubePose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_logic_node::CubePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] position \n"
"string colour\n"
;
  }

  static const char* value(const ::control_logic_node::CubePose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_logic_node::CubePose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.colour);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubePose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_logic_node::CubePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_logic_node::CubePose_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "colour: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.colour);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_LOGIC_NODE_MESSAGE_CUBEPOSE_H
