// Generated by gencpp from file control_logic_node/DesJointState.msg
// DO NOT EDIT!


#ifndef CONTROL_LOGIC_NODE_MESSAGE_DESJOINTSTATE_H
#define CONTROL_LOGIC_NODE_MESSAGE_DESJOINTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_logic_node
{
template <class ContainerAllocator>
struct DesJointState_
{
  typedef DesJointState_<ContainerAllocator> Type;

  DesJointState_()
    : thetas()  {
      thetas.assign(0.0);
  }
  DesJointState_(const ContainerAllocator& _alloc)
    : thetas()  {
  (void)_alloc;
      thetas.assign(0.0);
  }



   typedef boost::array<float, 5>  _thetas_type;
  _thetas_type thetas;





  typedef boost::shared_ptr< ::control_logic_node::DesJointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_logic_node::DesJointState_<ContainerAllocator> const> ConstPtr;

}; // struct DesJointState_

typedef ::control_logic_node::DesJointState_<std::allocator<void> > DesJointState;

typedef boost::shared_ptr< ::control_logic_node::DesJointState > DesJointStatePtr;
typedef boost::shared_ptr< ::control_logic_node::DesJointState const> DesJointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_logic_node::DesJointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_logic_node::DesJointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_logic_node::DesJointState_<ContainerAllocator1> & lhs, const ::control_logic_node::DesJointState_<ContainerAllocator2> & rhs)
{
  return lhs.thetas == rhs.thetas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_logic_node::DesJointState_<ContainerAllocator1> & lhs, const ::control_logic_node::DesJointState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_logic_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_logic_node::DesJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_logic_node::DesJointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_logic_node::DesJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_logic_node::DesJointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_logic_node::DesJointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_logic_node::DesJointState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_logic_node::DesJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcf2dca9789fea2e3dbb6efc5dedb2ad";
  }

  static const char* value(const ::control_logic_node::DesJointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcf2dca9789fea2eULL;
  static const uint64_t static_value2 = 0x3dbb6efc5dedb2adULL;
};

template<class ContainerAllocator>
struct DataType< ::control_logic_node::DesJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_logic_node/DesJointState";
  }

  static const char* value(const ::control_logic_node::DesJointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_logic_node::DesJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[5] thetas\n"
;
  }

  static const char* value(const ::control_logic_node::DesJointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_logic_node::DesJointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.thetas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DesJointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_logic_node::DesJointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_logic_node::DesJointState_<ContainerAllocator>& v)
  {
    s << indent << "thetas[]" << std::endl;
    for (size_t i = 0; i < v.thetas.size(); ++i)
    {
      s << indent << "  thetas[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.thetas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_LOGIC_NODE_MESSAGE_DESJOINTSTATE_H
