// Generated by gencpp from file control_logic_node/DesPosition.msg
// DO NOT EDIT!


#ifndef CONTROL_LOGIC_NODE_MESSAGE_DESPOSITION_H
#define CONTROL_LOGIC_NODE_MESSAGE_DESPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_logic_node
{
template <class ContainerAllocator>
struct DesPosition_
{
  typedef DesPosition_<ContainerAllocator> Type;

  DesPosition_()
    : position()
    , orientation_z(0.0)  {
      position.assign(0.0);
  }
  DesPosition_(const ContainerAllocator& _alloc)
    : position()
    , orientation_z(0.0)  {
  (void)_alloc;
      position.assign(0.0);
  }



   typedef boost::array<float, 3>  _position_type;
  _position_type position;

   typedef float _orientation_z_type;
  _orientation_z_type orientation_z;





  typedef boost::shared_ptr< ::control_logic_node::DesPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_logic_node::DesPosition_<ContainerAllocator> const> ConstPtr;

}; // struct DesPosition_

typedef ::control_logic_node::DesPosition_<std::allocator<void> > DesPosition;

typedef boost::shared_ptr< ::control_logic_node::DesPosition > DesPositionPtr;
typedef boost::shared_ptr< ::control_logic_node::DesPosition const> DesPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_logic_node::DesPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_logic_node::DesPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_logic_node::DesPosition_<ContainerAllocator1> & lhs, const ::control_logic_node::DesPosition_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.orientation_z == rhs.orientation_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_logic_node::DesPosition_<ContainerAllocator1> & lhs, const ::control_logic_node::DesPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_logic_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_logic_node::DesPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_logic_node::DesPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_logic_node::DesPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_logic_node::DesPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_logic_node::DesPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_logic_node::DesPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_logic_node::DesPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e2aade9b104799c49e86da7da995598";
  }

  static const char* value(const ::control_logic_node::DesPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e2aade9b104799cULL;
  static const uint64_t static_value2 = 0x49e86da7da995598ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_logic_node::DesPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_logic_node/DesPosition";
  }

  static const char* value(const ::control_logic_node::DesPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_logic_node::DesPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] position\n"
"float32 orientation_z\n"
;
  }

  static const char* value(const ::control_logic_node::DesPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_logic_node::DesPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DesPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_logic_node::DesPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_logic_node::DesPosition_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "orientation_z: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_LOGIC_NODE_MESSAGE_DESPOSITION_H
